companies = {
    "Technology": {
        "Apple": "AAPL",
        "Microsoft": "MSFT",
        "Amazon": "AMZN",
        "Alphabet (Google)": "GOOGL",
        "Meta Platforms": "META",
        "Netflix": "NFLX",
        "NVIDIA": "NVDA",
        "Intel": "INTC",
        "IBM": "IBM",
        "Oracle": "ORCL",
        "Salesforce": "CRM",
        "Adobe": "ADBE",
        "PayPal": "PYPL",
        "Cisco Systems": "CSCO",
        "Texas Instruments": "TXN",
        "Advanced Micro Devices": "AMD",
        "Qualcomm": "QCOM",
        "Broadcom": "AVGO",
        "Taiwan Semiconductor": "TSM",
        "SAP": "SAP"
    },
    "Retail": {
        "Walmart": "WMT",
        "Target": "TGT",
        "Costco": "COST",
        "Home Depot": "HD",
        "Lowe's": "LOW",
        "Best Buy": "BBY",
        "TJX Companies": "TJX",
        "Dollar General": "DG",
        "Kroger": "KR",
        "Walgreens Boots Alliance": "WBA"
    },
    "Automotive": {
        "Tesla": "TSLA",
        "General Motors": "GM",
        "Ford": "F",
        "Toyota": "TM",
        "Honda": "HMC",
        "Ferrari": "RACE",
        "Volkswagen": "VWAGY",
        "BMW": "BMWYY",
        "Daimler (Mercedes-Benz)": "DDAIF",
        "Stellantis": "STLA"
    },
    "Finance": {
        "JPMorgan Chase": "JPM",
        "Bank of America": "BAC",
        "Wells Fargo": "WFC",
        "Citigroup": "C",
        "Goldman Sachs": "GS",
        "Morgan Stanley": "MS",
        "Visa": "V",
        "Mastercard": "MA",
        "American Express": "AXP",
        "BlackRock": "BLK",
        "Charles Schwab": "SCHW"
    },
    "Healthcare": {
        "Johnson & Johnson": "JNJ",
        "Pfizer": "PFE",
        "UnitedHealth Group": "UNH",
        "Merck": "MRK",
        "Abbott Laboratories": "ABT",
        "Eli Lilly": "LLY",
        "Gilead Sciences": "GILD",
        "Amgen": "AMGN",
        "Bristol-Myers Squibb": "BMY",
        "Moderna": "MRNA",
        "Thermo Fisher Scientific": "TMO"
    },
    "Energy": {
        "ExxonMobil": "XOM",
        "Chevron": "CVX",
        "Shell": "SHEL",
        "BP": "BP",
        "TotalEnergies": "TTE",
        "ConocoPhillips": "COP",
        "Schlumberger": "SLB",
        "Occidental Petroleum": "OXY",
        "Enbridge": "ENB",
        "Kinder Morgan": "KMI"
    },
    "Consumer Goods": {
        "Procter & Gamble": "PG",
        "Coca-Cola": "KO",
        "PepsiCo": "PEP",
        "Unilever": "UL",
        "Nestlé": "NSRGY",
        "Nike": "NKE",
        "Adidas": "ADDYY",
        "Colgate-Palmolive": "CL",
        "Estée Lauder": "EL",
        "Kimberly-Clark": "KMB"
    },
    "Telecommunications": {
        "AT&T": "T",
        "Verizon": "VZ",
        "T-Mobile": "TMUS",
        "Comcast": "CMCSA",
        "Vodafone": "VOD",
        "Deutsche Telekom": "DTEGY",
        "Orange": "ORAN",
        "China Mobile": "CHL",
        "SoftBank Group": "SFTBY",
        "América Móvil": "AMX"
    },
    "Aerospace & Defense": {
        "Boeing": "BA",
        "Lockheed Martin": "LMT",
        "Northrop Grumman": "NOC",
        "Raytheon Technologies": "RTX",
        "General Dynamics": "GD",
        "Airbus": "EADSY",
        "BAE Systems": "BAESY",
        "L3Harris Technologies": "LHX",
        "Textron": "TXT",
        "Rolls-Royce": "RYCEY"
    },
    "Entertainment & Media": {
        "Walt Disney": "DIS",
        "Comcast": "CMCSA",
        "ViacomCBS": "VIAC",
        "Sony": "SONY",
        "Live Nation Entertainment": "LYV",
        "Electronic Arts": "EA",
        "Activision Blizzard": "ATVI",
        "Take-Two Interactive": "TTWO",
        "Warner Bros. Discovery": "WBD",
        "Fox Corporation": "FOX"
    }
}